version: '3.9'

services:
  app:
    image: ${DOCKER_USERNAME}/care-link:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}

      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      SMS_API_KEY: ${SMS_API_KEY}
      SMS_API_SECRET_KEY: ${SMS_API_SECRET_KEY}
      SMS_FROM_PHONE_NUMBER: ${SMS_FROM_PHONE_NUMBER}

    restart: always
