spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 10MB
  datasource:
    url: jdbc:h2:mem:~/carelink;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          exception-handling: ignore
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: test
            client-secret: test
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              profile,
              email,
              nickname
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
logging:
  level:
    root: info  # 전체 로그를 INFO, DEBUG, WARN 수준으로 설정
    org.springframework.security: DEBUG
    com.blaybus.server: info

carelink:
  control:
    jwtSecret: "======== THIS IS CARE LINK TEST KEY ========"
    jwtAccessExpiration: 1800000
    jwtRefreshExpiration: 3600000

s3:
  accessKey: test
  secretKey: test
  region: test
  bucketName: test

sms:
  apiKey: test
  apiSecretKey: test
  apiHost: http://test
  fromPhoneNumber: test

